### ISSUE TITLE
Fix the 'previous' and 'next' navigation or remove it

### ISSUE THREAD

**Issue by aschrijver** [humanetech-community/community-hub#28]
The navigation to previous and next pages is not working properly. For example this page:

`https://humanetech.community/focus/harms-of-technology/`

Has previous page be `Pyramid of Technology Alignment` (which is correct), but next leads to `Pyramid of Freedom / Openness`

**Comment by aschrijver** [comment]
This probably involves cleaning the file structure. In our haste to get the MVP up and also have Search working, all markdown pages are in `_Docs`, but the structure should probably be like this:

- `_Docs`
  - all markdown pages in docs structure in a flat list, and nrs. in filename for alphabetic sorting
- `_About`
  - same, but for About section
- etcetera

This requires defining them in `_config.yml`.

**Edit**: My quick typing above is probably not how this is intended to work. Looking at `minimal-mistakes` now shows that it is not done like that there as well.

**Comment by henryrowswell** [comment]
I think I can tackle this! But I need to clarify the intended ordering of the docs. Starting from `/docs/`, should the ordering follow the ordering laid out in the `focusarea` nav? This would make the most sense to me since each page leads to the next one in the sidebar, but I'm not sure if the original intent was to follow a more complex ordering, seeing as there are also sidebar navs for `topleveldocs` or `harms` that skip over certain subpages.

**Comment by aschrijver** [comment]
Yes, you are right. This needs a bit more thinking. I rather take on this issue myself if you don't mind. Have to think about intended navigation structure a bit more.

**Comment by aschrijver** [comment]
The ordering should at least be chronologically logical. Now there are strange jumps when pressing 'Next'. Yes `docs` should follow the document structure from the left-bar, then when at the end of this set of pages jump to the next top-level item and drill down into that left sidebar navigation.

**Comment by aschrijver** [comment]
Great PR @henryrowswell and navigation works like a charm.
