### ISSUE TITLE
Option to remove "suggested topics" at the end of the message list 

### ISSUE THREAD

**Issue by polterguess** [humanetech-community/community-hub#55]
I find it jarring to see a list of old dead topics in a suggest list looking very bold and loud.

Possible Solutions:
1. Give user option to turn on or off this feature
2. BEST - Collapse it, so you can open it to look inside but it's not visible until you open it.
3. FAST - Tone it down with light grey text font
4. Add a much larger space between the end of the message and this dump

**Comment by aschrijver** [comment]
We consider the HTC forum to consist of an 'Archive' of content waiting to be processed. In that sense there are no 'old dead topics'. They are not dead, but just slid out of view by new topics coming in. We encourage anyone to make crossreferences to older topics, so that things are more easy to find.

But ultimately we want to use the knowledge, wisdom and insights of forum topics when creating Documentation on the Community Hub. 

The 'Suggested Topics' however is indeed something that could be removed. I never use them myself, and looking at some example suggestions they seem not to be the most relevant ones. 

I created a Feedback topic on the forum for this: https://community.humanetech.com/t/3979
