### ISSUE TITLE
End of Message format - 90% of the time, you just want to reply

### ISSUE THREAD

**Issue by polterguess** [humanetech-community/community-hub#56]
At the end of a message, mostly what we need is the "REPLY" button.
Please tone down the other buttons that RARELY get used.

Possible solutions
1. FAST - Put the reply button on it's own line cleanly below the last message.
2. FAST - Shrink the size and light grey the RARELY used options of "share" etc etc.
3. HARD - Or hide these other options behind one 'other' button.
4. FAST - just add spacing between the REPLY (used a lot) and the others (RARE).

**Comment by henryrowswell** [comment]
Hey Chris! It seems to me for this issue and #55 you're referring to the forum specifically, rather than the "community hub"? By forum I mean https://community.humanetech.com/, vs the hub which is https://humanetech.community/, the urls are kind of trippy haha.

I'm new so I could be wrong but from what I see I think the forum is run using [discourse](https://www.discourse.org/), and I'm not sure how much power we have to customize that, perhaps someone with admin privileges would know more. This repo is for the community hub which is a static site that I think simply links to the forum, but is independent of it so we wouldn't be able to modify the forum UI, at least not through the code here.

**Comment by polterguess** [comment]
Oh, ok, that makes sense. 

The forum code is not in the repo.

Thanks for the follow up!

**Comment by cdavies2014** [comment]
Hi Henry,

I don’t know if you saw all of the Video where Tristan Harris mentions the reddit spin off “Change my Mind”?

I have an idea for a much more powerful format of a table for a solution to this “debate” problem that could help people understand and debate issues on all the hot and painful topics.

I do have some basic coding skills, but I don’t know if you’re interesting in a “bigger” juicier project??

Thanks for reading,
Chris

**Comment by polterguess** [comment]
Oh, and you’re right - this community maybe could use slack in some capacity.

**Comment by aschrijver** [comment]
@cdavies2014 you can post forum-related things to the Feedback category there.

**Comment by aschrijver** [comment]
I added a 'forum' label for clarity.

Regarding your idea to 'tone down' the other buttons: In my UI they are toned down. The Reply is blue and the other buttons (which I do frequently use) are grey in color.
